services:

  postgres:
    container_name: postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - ./app_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  service:
    container_name: service
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      - postgres
